stages:
  - test
  - publish

test:
  stage: test
  image: docker.nabudev.hu/node-ci-image:latest
  tags:
    - arm64
  script:
    - pnpm install
    - pnpm test

publish:
  stage: publish
  image: docker.nabudev.hu/node-ci-image:latest
  tags:
    - arm64
  script:
    - auth-npm-registry "$REGISTRY_USER" "$REGISTRY_PASSWORD"
    - pnpm install
    - pnpm publish --no-git-checks
